### ISSUE TITLE
Loading primitives doesn't trigger events?

### ISSUE THREAD

**Issue by ASoldo** [Plumie/Norska#14]
Hi, when loading `.glb` file with `x-3.primitive` I was not able to get logs in console while with `x-3.mesh` i did get events triggered.
```html
<br x-3.primitive="(await $load($loaders.GLTFLoader, 'assets/Cuba.glb')).scene"
  x-effect="$frame(() => {$i.rotation.y += 0.01; $i.rotation.x += 0.01;})" @click="() => console.log('click')"
  @contextMenu="() => console.log('context menu')" @dblClick="() => console.log('double click')"
  @wheel="() => console.log('wheel spins')" @pointerUp="() => console.log('up')"
  @pointerDown="() => console.log('down')" @pointerOver="() => console.log('over')"
  @pointerIn="() => console.log('in')" @pointerOut="() => console.log('out')"
  @pointerMove="() => console.log('move')" />
```

This is the code markdown that I'm trying to use on custom loaded .glb files. Am I doing something wrong? I tried to wrap it in div with `x-3.mesh` but it doesn't do anything.

**Comment by Plumie** [comment]
Maybe it has something to do with my raycast implementation, I'll try to reproduce the problem on my side as soon as possible and get back to you!

**Comment by Plumie** [comment]
https://github.com/Plumie/Norska/releases/tag/0.4.2 should fix it, can you try ?

**Comment by ASoldo** [comment]
Now it's working! Thank you!
